config/routes.rb
Rails.application.routes.draw do
  resources :popups
  mount Ckeditor::Engine => '/ckeditor'
  root 'pages#home'
  get 'pages/galleries' => 'pages#galleries'
  get 'setting/general' => 'setups#general'
  resources :setups
  get 'genres/search' => 'genres#search'
  resources :genres
  get 'artists/search' => 'artists#search'
  get 'artists/all' => 'artists#all'
  resources :contacts
  resources :artists
  resources :images
  resources :venues
  get 'events/all' => 'events#all'
  get 'events/preview/:id' => 'events#preview', as: :events_preview
  get 'events/search' => 'events#search'
  get 'events/to_trash/:id' => 'events#to_trash', as: :events_to_trash
  resources :events
  get 'posts/all' => 'posts#all'
  get 'posts/preview/:id' => 'posts#preview', as: :posts_preview
  get 'posts/search' => 'posts#search'
  get 'posts/to_trash/:id' => 'posts#to_trash', as: :posts_to_trash
  resources :posts do
    resources :videos
    resources :audios
  end
  get 'pages/preview/:id' => 'pages#preview', as: :pages_preview
  get 'pages/search' => 'pages#search'
  get 'pages/to_trash/:id' => 'pages#to_trash', as: :pages_to_trash
  resources :pages
  get 'categories/search' => 'categories#search'
  resources :categories
  get 'cms-admin' => 'cms_admin#index'
  devise_for :users
  resources :users
  resources :tags
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_and_belongs_to_many :genres
    # belongs_to :image
    # belongs_to :video
    # belongs_to :audio
    extend FriendlyId
    friendly_id :name, use: :slugged
    mount_uploader :artist_portrait, FeatureUploader
    validates :name, presence: true
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :all]
  layout 'admin', except: [:show, :all]
  include PagesHelper
  include ArtistsHelper
  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all.order(:name)
    @artists = Kaminari.paginate_array(@artists).page(params[:page]).per(20)
  end

  def search
    if params[:keyword].present?
      @artists = Artist
      if params[:keyword].present?
        if Rails.env.production?
          @artists = @artists.where(["artists.name ILIKE ?", "%#{params[:keyword]}%"])
        else
          @artists = @artists.where(["artists.name LIKE ?", "%#{params[:keyword]}%"])
        end
      end
      @artists = Kaminari.paginate_array(@artists).page(params[:page]).per(20)
    else
      @artists = Artist.order(:name)
      @artists = Kaminari.paginate_array(@artists).page(params[:page]).per(20)
    end
    render 'index'
  end

  def all
    @artists = Artist.all.order(:name)
    @artists = Kaminari.paginate_array(@artists).page(params[:page]).per(20)
    page_meta_data(Page.where(slug: 'all-artists').first) if Page.where(slug: 'all-artists').present?
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @genres = @artist.genres
    @artists = Artist.all.order(:name)
    @post_videos = Post.where(status: 'publish').where(post_format: 'video').includes(:videos).where('videos.artist_id = ?', @artist.id).references(:videos)
    @post_images = Post.where(status: 'publish').where(post_format: 'image').includes(:images).where('images.artist_id = ?', @artist.id).references(:images)
    artist_meta_data(@artist)
    @events = Event.where(status: 'publish').limit(5).order(start_date: :asc)
  end

  # GET /artists/new
  def new
    @artist = Artist.new
    @genres = Genre.order(:name)
  end

  # GET /artists/1/edit
  def edit
    @genres = Genre.order(:name)
  end

  # POST /artists
  # POST /artists.json
  def create
    @genres = Genre.order(:name)
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to artists_path, notice: 'Artist was successfully created.' }
        format.json { render :index, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    @genres = Genre.order(:name)
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to edit_artist_path(@artist), notice: 'Artist was successfully updated.' }
        format.json { render :edit, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artist_params
      params.require(:artist).permit(:name, :slug, :role, :description, :seo_title, :focus_keyphrase, :meta_description, :artist_portrait, :genre_ids => [])
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
  def artist_meta_data(artist)
    setup = Setup.find(1)

    if artist.seo_title.present?
      title = artist.seo_title
    else
      title = artist.name
    end
    
    desc = ActionView::Base.full_sanitizer.sanitize(artist.meta_description).truncate(150)
    if artist.artist_portrait.blank? || artist.artist_portrait.nil?
      image = ''
    else
      image = setup.site_url + artist.artist_portrait.url
    end

    keywords = artist.focus_keyphrase if artist.focus_keyphrase.present?
    
    prepare_meta_tags(
      title: title, description: desc,image:image, keywords: keywords,
      twitter:{
        title: title + ' - ' + setup.site_name,
        description:desc,
        image:image,
        site_name: "#{setup.site_name} | #{title}",
        card: 'summary'
      },
      og:{
        url:request.original_url,
        site_name: setup.site_name,
        title: title + ' - ' + setup.site_name,
        description:desc,
        image:image,
        type:'article'
      }
    )
  end
end

app/views/artists/_form.html.erb
<% if @artist.errors.any? %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-danger" role="alert">
        <h3 class="alert-heading"><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h3>
        <ul>
          <% @artist.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-md-12">
    <% unless @artist.new_record? %>
      <a href="<%= artist_path(@artist) %>" class="btn btn-info mb-2" target="_blank">Preview</a>
    <% end %>
    <div class="card">
      <div class="card-body">
        <%= form_for @artist, :html => { :class => "form-horizontal artist" } do |f| %>
          <div class="row form-group">
            <%= f.label :artist_portrait, :class => 'col-form-label col-lg-2 text-capitalize' %>
            <div class="col-lg-4">
              <% if @artist.artist_portrait.nil? %>
                <%= f.file_field :artist_portrait, :class => 'dropify','data-max-file-size'=>'1M', 'data-allowed-formats' => 'square', 'data-allowed-file-extensions' => 'jpg png jpeg'  %>
              <% else %>
                <%= f.file_field :artist_portrait, :class => 'dropify','data-max-file-size'=>'1M', 'data-allowed-formats' => 'square', 'data-allowed-file-extensions' => 'jpg png jpeg', 'data-default-file' => @artist.artist_portrait.url %>
              <% end %>
              <%=f.error_span(:artist_portrait) %>
            </div>
          </div>
          <div class="row form-group">
            <%= f.label :name, :class => 'col-form-label col-lg-2' %>
            <div class="col-lg-4">
              <%= f.text_field :name, :class => 'form-control', :required => true %>
              <%=f.error_span(:name) %>
            </div>
            <div class="col-md-6">
              <small><em>*required</em></small>
            </div>
          </div>
          <% unless @artist.new_record? %>
            <div class="row form-group">
              <%= f.label :slug, :class => 'col-form-label col-lg-2' %>
              <div class="col-lg-4">
                <%= f.text_field :slug, :class => 'form-control', :required => true %>
                <%=f.error_span(:slug) %>
              </div>
            </div>
          <% end %>
          <div class="row form-group">
            <%= f.label :role, :class => 'col-form-label col-lg-2' %>
            <div class="col-lg-4">
              <%= f.text_field :role, :class => 'form-control' %>
              <%=f.error_span(:role) %>
            </div>
          </div>
          <div class="row form-group">
            <label class="col-form-label col-lg-2">Genre</label>
            <div class="col-md-10">
              <ul class="p-0" style="list-style-type: none;">
                <%= f.collection_check_boxes :genre_ids, @genres, :id, :name do |item| %>
                <li class="mr-2 mb-2">
                  <div class="custom-control custom-checkbox">
                    <%= item.check_box class: "custom-control-input" %>
                    <%= item.label class: 'custom-control-label' %>
                  </div>
                </li>
                <% end %>
              </ul>
            </div>
          </div>
          <div class="row form-group">
            <%= f.label :description, :class => 'col-form-label col-lg-2' %>
            <div class="col-lg-10">
              <%= f.cktext_area :description, :class => 'form-control' %>
              <%=f.error_span(:description) %>
            </div>
          </div>
          <div class="row form-group">
            <%= f.label :seo_title, :class => 'col-form-label col-lg-2 text-capitalize' %>
            <div class="col-lg-10">
              <%= f.text_field :seo_title, :class => 'form-control' %>
              <%=f.error_span(:seo_title) %>
            </div>
          </div>
          <div class="row form-group">
            <%= f.label :focus_keyphrase, :class => 'col-form-label col-lg-2 text-capitalize' %>
            <div class="col-lg-10">
              <%= f.text_field :focus_keyphrase, :class => 'form-control' %>
              <%=f.error_span(:focus_keyphrase) %>
            </div>
          </div>
          <div class="row form-group">
            <%= f.label :meta_description, :class => 'col-form-label col-lg-2 text-capitalize' %>
            <div class="col-lg-10">
              <%= f.text_area :meta_description, :class => 'form-control', rows: '5' %>
              <%=f.error_span(:meta_description) %>
            </div>
          </div>
          <div class="row form-group">
            <div class="col-md-10 offset-md-2">
              <%= f.submit nil, :class => 'btn btn-success' %>
              <% unless @artist.new_record? %>
                <%= link_to "<i class='fas fa-times-circle'></i> Destroy".html_safe, artist_path(@artist), :class => 'btn waves-effect waves-light btn-danger', :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
              <% end %>
              <%= link_to t('.cancel', :default => t("helpers.links.cancel")), artists_path, :class => 'btn btn-secondary' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/artists/_search.html.erb
<div class="mb-1">
    <%= form_tag({action: :search}, method: 'get') do %>
        <div class="form-row">
            <div class="input-group mb-2 col">
                <%= text_field_tag :keyword, (params[:keyword] or '') , options={class: "form-control", placeholder: "Insert Keyword Here"} %>
            </div>
            <button type="submit" class="btn btn-primary mb-2">Search</button>
        </div>
    <% end %>
</div>

app/views/artists/all.html.erb
<div class="background-parallax" style="background-image:url('<%= asset_path('djvideo2.jpg') %>'); ">
	<div class="background-layer-opacity-black">
	</div>
  <div class="container">
    <section class="mb-6 pt-5">
      <div class="row">
        <div class="col-md-12">
          <div class="col-md-12 section-title-block mb-4">
            <h1 class="text-uppercase text-white page-title">artists</h1>
          </div>
          <div class="row text-white mb-4 justify-content-center">
            <% @artists.each do |artist| %>
              <div class="col-md-3 mb-4">
                <a href="<%= artist_path(artist) %>" class="news-card-link"></a>
                <img src="<%= artist.artist_portrait.url %>" alt="" class="w-100 mb-2">
                <h2 class="artist-gallery-name text-uppercase text-white"><%= artist.name %></h2>
                <p class="text-warning letter-spacing-3 text-uppercase artist-role">
                  <% artist.genres.take(5).each do |genre| %>
                    <% if genre == artist.genres.take(5)[artist.genres.take(5).length.to_i - 1] %>
                      <%= genre.name %>
                    <% else %>
                      <%= genre.name + ',' %>
                    <% end %>
                  <% end %>
                </p>
              </div>
            <% end %>
          </div>
          <div class="row mb-4">
            <div class="col-md-12 text-center">
              <%= paginate @artists %>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>
<%= show_popup(0) %>

app/views/artists/edit.html.erb
<%- model_class = Artist -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page"><a href="<%= artists_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item active"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/artists/index.html.erb
<%- model_class = Artist -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page">
              <a href="<%= artists_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a>
            </li>
            <li class="breadcrumb-item active">All <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <%= link_to "<i class='fas fa-plus-circle'></i> Add New".html_safe, new_artist_path, :class => 'btn waves-effect waves-light btn-rounded btn-success mb-2' %>
      <%= render partial: 'search' %>
      <div class="card">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th class="text-center"><%= model_class.human_attribute_name(:id) %></th>
                  <th class="text-center text-capitalize"><%= model_class.human_attribute_name(:artist_portrait) %></th>
                  <th class="text-center"><%= model_class.human_attribute_name(:name) %></th>
                  <th class="text-center"><%= model_class.human_attribute_name(:created_at) %></th>
                  <th class="text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
                </tr>
              </thead>
              <tbody>
                <% @artists.each do |artist| %>
                  <tr>
                    <td class="text-center"><%= link_to artist.id, artist_path(artist) %></td>
                    <td class="text-center">
                      <img src="<%= artist.artist_portrait.url %>" alt="" style="width:200px;">
                    </td>
                    <td class="text-center"><%= artist.name %></td>
                    <td class="text-center"><%= artist.created_at.strftime("%Y/%m/%d@%H:%M:%S") %></td>
                    <td class="text-center">
                      <%= link_to "<i class='fas fa-eye'></i> Show".html_safe, artist_path(artist), :class => 'btn-sm waves-effect waves-light btn-info mb-1', target: '_blank' %>
                      <%= link_to "<i class='fas fa-edit'></i> Edit".html_safe, edit_artist_path(artist), :class => 'btn-sm waves-effect waves-light btn-warning mb-1' %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <%= paginate @artists %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/artists/new.html.erb
<%- model_class = Artist -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page">
              <a href="<%= artists_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a>
           </li>
            <li class="breadcrumb-item active"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/artists/show.html.erb
<%- model_class = Artist -%>
<div class="background-parallax" style="background-image:url('<%= asset_url('djvideo2.jpg') %>'); ">
  <div class="background-layer-opacity-black">
  </div>
  <div class="container">
    <section class="mb-6 pt-5">
      <div class="row">
        <div class="col-md-9">
          <div class="col-md-12 section-title-block mb-4">
            <h1 class="text-uppercase text-white page-title">artist: <%= @artist.name %></h1>
          </div>
          <div class="row">
            <div class="col-md-4 text-white">
              <% if @artist.artist_portrait.present? %>
                <img src="<%= @artist.artist_portrait.url %>" alt="" class="w-100 mb-3">
              <% else %>
                <img src="<%= asset_path 'no-thumbnail' %>" alt="" class="w-100 mb-3">
              <% end %>
              <p>
                <strong class="text-warning">Name:</strong><br>
                <%= @artist.name %>
              </p>
              <p>
                <strong class="text-warning">Role:</strong><br>
                <%= @artist.role %>
              </p>
              <p>
                <strong class="text-warning">Genre:</strong><br>
                <% @genres.each do |genre| %>
                  <% if genre == @genres[@genres.length.to_i - 1] %>
                      <%= genre.name %>
                  <% else %>
                    <%= genre.name + ',' %>
                  <% end %>
                <% end %>
              </p>
            </div>
            <div class="col-md-8 text-white">
              <%= @artist.description.html_safe %>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="col-md-12 section-title-block mb-4">
            <h2 class="text-uppercase text-white section-title">upcoming events</h2>
          </div>
          <% if @events.present? %>
            <% @events.limit(3).each do |event| %>
              <div class="row mb-5">
                <div class="col-md-12">
                  <h3 class="mb-3 text-warning event-title"><%= event.title %></h3>
                </div>
                <div class="col-md-3 col-3">
                  <% if event.start_date.present? %>
                    <p class="text-white text-center upcoming-event-date">
                      <span class="event-day-number"><%= event.start_date.strftime("%d") %></span><br>
                      <span><%= event.start_date.strftime("%b") %></span>
                    </p>
                  <% end %>
                </div>
                <div class="col-md-9 col-9">
                  <% if event.start_date.present? && event.finish_date.present? %>
                    <p class="text-white"><i class="fas fa-clock"></i> <%= event.start_date.strftime("%H:%M %p") %> - <%= event.finish_date.strftime("%H:%M %p") %></p>
                  <% end %>
                  <% if event.venue.present? %>
                    <p class="text-white"><i class="fas fa-location-arrow"></i> <%= event.venue.title %></p>
                  <% end %>
                </div>
                <div class="col-md-12 text-right">
                  <a href="<%= event_path(event) %>" class="btn btn-warning">More Details</a>
                </div>
              </div>
            <% end %>
            <div class="row mb-3">
              <div class="col-md-12 text-center">
                <a href="<%= events_all_path %>" class="btn btn-lg btn-outline-warning">View More</a>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </section>
    <% if @post_images.present? %>
      <section class="pb-6">
        <div class="col-md-12 section-title-block mb-4">
          <h2 class="text-uppercase text-white section-title">images</h2>
        </div>
        <div class="row justify-content-center">
          <% @post_images.each do |post| %>
            <% post.images.order(created_at: :desc).each do |image| %>
              <div class="col-md-3 mb-3 text-center">
                <%
                  if image.file.present?
                    image_thumbnail = image.file.url
                  else
                    image_thumbnail = asset_path 'no-thumbnail'
                  end
                %>
                <div class="news-thumbnail" style="background-image:url('<%= image_thumbnail %>')">
                  <a href="" class="album-card-link" data-toggle="modal" data-target="#image<%= image.id %>"></a>
                </div>
                <a href="<%= post_path(post) %>" class="text-warning news-title">
                  <p><%= image.caption if image.caption.present? %></p>
                </a>
              </div>
              <div class="modal fade" id="image<%= image.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                  <div class="modal-content">
                    <div class="modal-body">
                      <img src="<%= image.file.url %>" alt="" class="w-100">
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </section>
    <% end %>
    <% if @post_videos.present? %>
      <section class="pb-6">
        <div class="col-md-12 section-title-block mb-4">
          <h2 class="text-uppercase text-white section-title">videos</h2>
        </div>
        <div class="row justify-content-center">
          <% @post_videos.each do |post|  %>
            <% post.videos.order(created_at: :desc).each do |video| %>
              <div class="col-md-3 mb-3 text-center">
                <%
                  if video.thumbnail_image.present?
                    video_thumbnail = video.thumbnail_image.url
                  else
                    video_thumbnail = asset_path 'no-thumbnail'
                  end
                %>
                <div class="news-thumbnail" style="background-image:url('<%= video_thumbnail %>')">
                  <a href="" class="album-card-link" data-toggle="modal" data-target="#video<%= video.id %>"></a>
                </div>
                <a href="" class="text-warning news-title" data-toggle="modal" data-target="#video<%= video.id %>">
                  <p><%= video.title %></p>
                </a>
              </div>
              <% if video.file.present? || video.video_url.present? %>
                <div class="modal fade" id="video<%= video.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                    <div class="modal-content">
                      <div class="modal-body">
                        <% if video.file.present? %>
                          <video controls width="100%" height="400" src="<%= video.file %>"></video>
                        <% end %>
                        <% if video.video_url.present? %>
                          <iframe width="100%" height="500" src="http://www.youtube.com/embed/<%= video.video_url.delete_prefix("https://www.youtube.com/watch?v=") %>" frameborder="0"></iframe>
                        <% end %>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </section>
    <% end %>
    <section class="pb-6">
      <div class="col-md-12 section-title-block mb-4">
        <h2 class="text-uppercase text-white section-title">our artists</h2>
      </div>
      <div class="owl-carousel">
        <% @artists.each do |artist| %>
          <div class="p-2">
            <div class="mb-3 artist-box">
              <img src="<%= artist.artist_portrait.medium_large.url %>" alt="" class="w-100">
              <div class="artist-details-layer">
                <div class="artist-details-background">
                </div>
                <div class="artist-details">
                  <a href="<%= artist_path(artist) %>" class="artist-link"></a>
                  <i class="fas fa-search artist-search-logo"></i>
                  <h3 class="text-uppercase text-white letter-spacing-3"><%= artist.name %></h3>
                  <p class="text-warning letter-spacing-3 text-uppercase artist-role">
                    <% artist.genres.take(5).each do |genre| %>
                      <% if genre == artist.genres.take(5)[artist.genres.take(5).length.to_i - 1] %>
                        <%= genre.name %>
                      <% else %>
                        <%= genre.name + ',' %>
                      <% end %>
                    <% end %>
                  </p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-md-12 text-center mt-3">
        <a href="#" class="btn btn-lg btn-outline-warning">View More</a>
      </div>
    </section>
  </div>
</div>
<%= show_popup(0) %>