config/routes.rb
Rails.application.routes.draw do
  resources :popups
  mount Ckeditor::Engine => '/ckeditor'
  root 'pages#home'
  get 'pages/galleries' => 'pages#galleries'
  get 'setting/general' => 'setups#general'
  resources :setups
  get 'genres/search' => 'genres#search'
  resources :genres
  get 'artists/search' => 'artists#search'
  get 'artists/all' => 'artists#all'
  resources :contacts
  resources :artists
  resources :images
  resources :venues
  get 'events/all' => 'events#all'
  get 'events/preview/:id' => 'events#preview', as: :events_preview
  get 'events/search' => 'events#search'
  get 'events/to_trash/:id' => 'events#to_trash', as: :events_to_trash
  resources :events
  get 'posts/all' => 'posts#all'
  get 'posts/preview/:id' => 'posts#preview', as: :posts_preview
  get 'posts/search' => 'posts#search'
  get 'posts/to_trash/:id' => 'posts#to_trash', as: :posts_to_trash
  resources :posts do
    resources :videos
    resources :audios
  end
  get 'pages/preview/:id' => 'pages#preview', as: :pages_preview
  get 'pages/search' => 'pages#search'
  get 'pages/to_trash/:id' => 'pages#to_trash', as: :pages_to_trash
  resources :pages
  get 'categories/search' => 'categories#search'
  resources :categories
  get 'cms-admin' => 'cms_admin#index'
  devise_for :users
  resources :users
  resources :tags
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_and_belongs_to_many :categories
  belongs_to :user
  belongs_to :venue, optional: true
  acts_as_taggable_on :tags
  mount_uploader :feature_image, FeatureUploader
  extend FriendlyId
  friendly_id :title, use: :slugged
  STATUS = [:publish, :draft, :trash]
  CURRENCY = [:usd, :idr, :eur, :sgd, :aud, :jpy]
  validates :title, presence: true
  validates :feature_image, file_size: { in: 1.kilobyte..1.megabyte }
  validates :price, numericality: {greater_than_or_equal_to: 0}
  validates :publish_date, presence: true
  scope :drafted, -> {where(status: 'draft')}
  scope :published, -> {where(status: 'publish')}
  scope :trashed, -> {where(status: 'trash')}
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :preview, :edit, :update, :destroy, :to_trash]
  before_action :authenticate_user!, except: [:show, :all]
  layout 'admin', except: [:show, :preview, :all]
  include CategoriesHelper
  include PagesHelper
  include EventsHelper
  # GET /events
  # GET /events.json
  def index
    @events = Event.where.not(status: "trash").order(created_at: :desc)
    @events = Kaminari.paginate_array(@events).page(params[:page]).per(20)
  end

  def search
    if params[:status].present? || params[:category].present? || params[:year].present? || params[:keyword].present?
      @events = Event
      if params[:keyword].present?
        if Rails.env.production?
          @events = @events.where(["events.title ILIKE ?", "%#{params[:keyword]}%"])
        else
          @events = @events.where(["events.title LIKE ?", "%#{params[:keyword]}%"])
        end
      end
      @events = @events.where(status: params[:status]) if params[:status].present?
      @events = @events.joins(:categories).where(categories: {id: params[:category]}).group("events.id") if params[:category].present?

      if params[:year].present?
        @events = @events.where(created_at: Date.new(params[:year].to_i).all_year)
        @events = @events.where(created_at: Date.new(params[:year].to_i, params[:month].to_i).all_month) if params[:month].present?  
      end
      @events = Kaminari.paginate_array(@events).page(params[:page]).per(20)
    else
      @events = Event.order(created_at: :desc)
      @events = Kaminari.paginate_array(@events).page(params[:page]).per(20)
    end
    render 'index'
  end

  def all
    @events = Event.where(status: 'publish').order(start_date: :asc)
    @events = Kaminari.paginate_array(@events).page(params[:page]).per(10)
    page_meta_data(Page.where(slug: 'all-events').first) if Page.where(slug: 'all-events').present?
  end
  
  # GET /events/1
  # GET /events/1.json
  def show
    @events = Event.where(status: 'publish').limit(5).order(start_date: :asc)
    event_meta_data(@event)
  end

  def preview
    render 'show'
  end

  # GET /events/new
  def new
    @event = Event.new
    @users = User.all
    @categories = order_by_subcategories()
    @venues = Venue.all
  end

  # GET /events/1/edit
  def edit
    @users = User.all
    @categories = order_by_subcategories()
    @venues = Venue.all
  end

  # POST /events
  # POST /events.json
  def create
    @users = User.all
    @categories = order_by_subcategories()
    @venues = Venue.all
    @event = Event.new(event_params)
    if params[:publish].present?
      @event.status = 'publish'
    else
      @event.status = 'draft'
    end
    respond_to do |format|
      if @event.save
        format.html { redirect_to edit_event_path(@event), notice: 'Event was successfully created.' }
        format.json { render :edit, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @users = User.all
    @categories = order_by_subcategories()
    @venues = Venue.all
    if params[:publish].present?
      @event.status = 'publish'
    else
      @event.status = 'draft'
    end
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to edit_event_path(@event), notice: 'Event was successfully updated.' }
        format.json { render :edit, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def to_trash
    respond_to do |format|
      if @event.update(status: 'trash')
        format.html { redirect_to events_path, notice: 'Event was successfully moved to trash.' }
        format.json { render :edit, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :slug, :publish_date, :status, :feature_image, :content, :start_date, :finish_date, :price, :currency, :seo_title, :focus_keyphrase, :meta_description, :user_id, :venue_id, :tag_list, :category_ids => [])
    end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_meta_data(event)
    setup = Setup.find(1)

    if event.seo_title.present?
      title = event.seo_title
    else
      title = event.title
    end
    
    desc = ActionView::Base.full_sanitizer.sanitize(event.meta_description).truncate(150)
    if event.feature_image.blank? || event.feature_image.nil?
      image = ''
    else
      image = setup.site_url + event.feature_image.url
    end

    keywords = event.focus_keyphrase if event.focus_keyphrase.present?
    
    prepare_meta_tags(
      title: title, description: desc,image:image, keywords: keywords,
      twitter:{
        title: title + ' - ' + setup.site_name,
        description:desc,
        image:image,
        site_name: "#{setup.site_name} | #{title}",
        card: 'summary'
      },
      og:{
        url:request.original_url,
        site_name: setup.site_name,
        title: title + ' - ' + setup.site_name,
        description:desc,
        image:image,
        type:'article'
      }
    )
  end
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-danger" role="alert">
        <h3 class="alert-heading"><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h3>
        <ul>
          <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>
<%= form_for @event, :html => { :class => "form-horizontal event" } do |f| %>
  <div class="row">
    <div class="col-md-8">
      <div class="form-group">
        <%= f.text_field :title, :class => 'form-control', placeholder: 'Insert Title Here', required: true, style: 'font-size:1.5rem;' %>
        <%=f.error_span(:title) %>
      </div>
      <% unless @event.new_record? %>
        <div class="row form-group">
          <%= f.label :slug, class: 'col-form-label col-md-2' %>
          <div class="col-md-10">
            <%= f.text_field :slug, :class => 'form-control' %>
            <%=f.error_span(:slug) %>
          </div>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.cktext_area :content, :class => 'form-control' %>
        <%=f.error_span(:content) %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group text-center">
        <% unless @event.new_record? %>
          <% if @event.status == 'publish' %>
            <%= link_to 'Show', event_path(@event), class: 'btn btn-info', target: '_blank' %>
          <% else %>
            <%= link_to 'Preview', events_preview_path(@event), class: 'btn btn-info', target: '_blank' %>
          <% end %>
        <% end %>
        <%= f.submit 'Save Draft', name: 'save_draft', :class => 'btn btn-light' %>
        <%= f.submit 'Publish', name: 'publish', :class => 'btn btn-success' %>
      </div>
      <div class="card">
        <div class="card-body">
          <% if @event.status.present? %>
            <div class="form-group">
              Status: <strong><%= @event.status.upcase %></strong>
            </div>
          <% end %>
          <div class="form-group">
            <%= f.label 'Author' %>
            <%= f.select :user_id, @users.map {|s| [s.username, s.id ]},{:include_blank => '-Choose Author-'}, :class=>"form-control w-100 select2", required: true %>
            <%=f.error_span(:user_id) %>
          </div>
          <div class="form-group">
            <%= f.label :publish_date, :class => 'text-capitalize' %>
            <%= f.datetime_field :publish_date, :class => 'form-control', required: true %>
            <%=f.error_span(:publish_date) %>
          </div>
          <% unless @event.new_record? %>
            <% unless @event.status == 'trash' %>
              <a href="<%= events_to_trash_path(@event) %>" class="btn btn-danger"><i class="fas fa-trash"></i> Move To Trash</a>
            <% end %>
          <% end %>
          <hr>
          <div class="form-group">
            <label>Categories</label>
            <div style="height:300px;overflow-y:scroll;border: 1px #cecece solid;padding: 0.5rem;">
              <ul class="p-0" style="list-style-type: none;">
                <%= f.collection_check_boxes :category_ids, @categories, :id, :name do |item| %>
                  <li class="mr-2 mb-2 <%= 'ml-3' if item.object.parent.present? %>">
                    <div class="custom-control custom-checkbox">
                      <%= item.check_box class: "custom-control-input" %>
                      <%= item.label class: 'custom-control-label' %>
                    </div>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :feature_image, class: 'text-capitalize' %>
            <% if @event.feature_image.nil? || @event.feature_image.blank? %>
              <%= f.file_field :feature_image, :class => 'dropify','data-max-file-size'=>'1M' %>
            <% else %>
              <%= f.file_field :feature_image, :class => 'dropify','data-max-file-size'=>'1M', 'data-default-file' => @event.feature_image.url %>
            <% end %>
            <%=f.error_span(:feature_image) %>
          </div>
          <div class="form-group">
            <%= f.label 'Tags' %>
            <%= f.text_field :tag_list, :class => 'event_tag_list', :value => @event.tag_list.join(",") %>
            <%=  @event.tag_list %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Venue Information</h3>
          <hr>
          <div class="row">
            <div class="col-md-6 form-group">
              <%= f.label :venue_id %>
              <%= f.select :venue_id, @venues.map {|s| [s.title, s.id ]},{:include_blank => '-Choose Venue-'}, :class=>"form-control w-100 select2" %>
              <%=f.error_span(:venue_id) %>
            </div>
            <div class="col-md-6 form-group">
              <%= f.label :price %>
              <div class="row">
                <%= f.select :currency, Event::CURRENCY.map {|r| [r.upcase, r] }, {:include_blank => '- Currency -'}, :class => 'form-control col-md-3' %>
                <%= f.number_field :price, :class => 'form-control col-md-9' %>
              </div>
              <%=f.error_span(:price) %>
            </div>
            <div class="col-md-6 form-group">
              <%= f.label :start_date, class: 'text-capitalize' %>
              <%= f.datetime_field :start_date, :class => 'form-control' %>
              <%=f.error_span(:start_date) %>
            </div>
            <div class="col-md-6 form-group">
              <%= f.label :finish_date, class: 'text-capitalize' %>
              <%= f.datetime_field :finish_date, :class => 'form-control' %>
              <%=f.error_span(:finish_date) %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">SEO</h3>
          <hr>
          <div class="row">
            <div class="col-md-6 form-group">
              <%= f.label :seo_title, class: 'text-capitalize' %>
              <%= f.text_field :seo_title, :class => 'form-control' %>
              <%=f.error_span(:seo_title) %>
            </div>
            <div class="col-md-6 form-group">
              <%= f.label :focus_keyphrase, class: 'text-capitalize' %>
              <%= f.text_field :focus_keyphrase, :class => 'form-control' %>
              <%=f.error_span(:focus_keyphrase) %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :meta_description, :class => 'text-capitalize' %>
            <%= f.text_area :meta_description, :class => 'form-control' %>
            <%=f.error_span(:meta_description) %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<script type="text/javascript">
  $('.event_tag_list').selectize({
    options:[
    <% ActsAsTaggableOn::Tag.all.each_with_index do |x, i|  %>
    {value:"<%= x %>", text:"<%= x %>"},
    <% end %>
    ],
    labelField: 'text',
    searchField: 'text',
    delimiter: ',',
    create: function(input) {
      return {
        value: input,
        text: input
      }
    }
  });
</script>

app/views/events/_nav_buttons.html.erb
<div>
    <a href="<%= events_path %>" class="btn waves-effect waves-light btn-rounded btn-outline-dark mb-2"> All</a>
    <a href="<%= events_search_path(status:'publish') %>" class="btn waves-effect waves-light btn-rounded btn-outline-dark mb-2"> Published</a>
    <a href="<%= events_search_path(status:'draft') %>" class="btn waves-effect waves-light btn-rounded btn-outline-dark mb-2"> Drafted</a>
    <a href="<%= events_search_path(status:'trash') %>" class="btn waves-effect waves-light btn-rounded btn-outline-dark mb-2"> Trash</a>
</div>

app/views/events/_search.html.erb
<% 
    @months = Event.select(:created_at).map{ |i| [Date::MONTHNAMES[i.created_at.month], i.created_at.month] }.uniq
    @years = Event.select(:created_at).map{ |i| i.created_at.year }.uniq
    @categories = Category.all.order(:name)
    @status = Event::STATUS.map {|r| [r.capitalize, r] }
%>
<div class="mb-1">
    <%= form_tag({action: :search}, method: 'get') do %>
        <div class="form-row">
            <div class="input-group mb-2 col">
                <%= select_tag :status, options_for_select(@status, :selected => params[:status]), include_blank: "Status", class:"form-control" %>
            </div>
            <div class="input-group mb-2 col">
                <%= select_tag :month, options_for_select(@months, :selected => params[:month]), include_blank: "Month", class:"form-control" %>
                <%= select_tag :year, options_for_select(@years, :selected => params[:year]), include_blank: "Year", class:"form-control" %>
                <div class="input-group-append">
                    <span class="input-group-text">
                        <span class="fas fa-calendar"></span>
                    </span>
                </div>
            </div>
            <div class="input-group mb-2 col">
                <%= select_tag :category, options_from_collection_for_select(@categories, "id", "name", :selected => params[:category]), include_blank: "All Categories", class:"form-control" %>
            </div>
            <div class="input-group mb-2 col">
                <%= text_field_tag :keyword, (params[:keyword] or '') , options={class: "form-control", placeholder: "Insert Keyword Here"} %>
            </div>
            <button type="submit" class="btn btn-primary mb-2">Search</button>
        </div>
    <% end %>
</div>

app/views/events/_table_event.html.erb
<% @events.each do |event| %>
  <tr>
    <td class="text-center"><%= link_to event.id, event_path(event) %></td>
    <td class="text-center"><%= event.title %></td>
    <td class="text-center text-uppercase"><%= event.status %></td>
    <td class="text-center">
      <% if event.start_date.present? %>
        Start: <br>
        <%= event.start_date.strftime("%Y/%m/%d@%H:%M:%S") %><br>
        Finish: <br>
        <%= event.finish_date.strftime("%Y/%m/%d@%H:%M:%S") if event.finish_date.present? %>
      <% end %>
    </td>
    <td class="text-center text-capitalize">
      <% if event.categories.present? %>
        <% event.categories.each_with_index do |cat, index| %>
          <% if (index+1) == event.categories.length %>
            <%= cat.name %>
          <% else %>
            <%= cat.name + ', ' %>
          <% end %>
        <% end %>
      <% end %>
    </td>
    <td class="text-center text-capitalize">
      <% if event.publish_date.present? %>
        Published:<br> <%= event.publish_date.strftime("%Y/%m/%d@%H:%M:%S") rescue '-' %><br>
      <% end %>
      Last Updated:<br> <%= event.updated_at.strftime("%Y/%m/%d@%H:%M:%S") rescue '-' %>
    </td>
    <td class="text-center text-capitalize">
      <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle btn-sm" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <% if event.status == 'publish' %>
            <%= link_to "<i class='fas fa-eye'></i> Show".html_safe, event_path(event), :class => 'dropdown-item', target: '_blank' %>
          <% else %>
            <%= link_to "<i class='fas fa-eye'></i> Preview".html_safe, events_preview_path(event), :class => 'dropdown-item', target: '_blank' %>
          <% end %>
          <%= link_to "<i class='fas fa-edit'></i> Edit".html_safe, edit_event_path(event), :class => 'dropdown-item' %>
          <% if event.status == 'trash' %>
            <%= link_to "<i class='fas fa-times-circle'></i> Destroy".html_safe, event_path(event), :class => 'dropdown-item', :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
          <% end %>
        </div>
      </div>
    </td>
  </tr>
<% end %>

app/views/events/all.html.erb
<div class="background-parallax" style="background-image:url('<%= asset_path('djvideo2.jpg') %>'); ">
	<div class="background-layer-opacity-black">
	</div>
  <div class="container">
    <section class="mb-6 pt-5">
      <div class="row">
        <div class="col-md-12">
          <div class="col-md-12 section-title-block mb-4">
            <h1 class="text-uppercase text-white page-title">events</h1>
          </div>
          <div class="row">
            <div class="col-md-12 text-white">
              <div class="table-responsive">
                <table class="table table-hover table-border">
                  <% @events.each do |event| %>
                    <tr>
                      <td class="table-cell-item">
                        <% if event.start_date.present? %>
                          <p class="text-white text-center mb-0">
                            <span class="event-day-number"><%= event.start_date.strftime("%d") %></span><br>
                            <span><%= event.start_date.strftime("%b") %></span>
                          </p>
                        <% end %>
                      </td>
                      <td class="table-cell-item table-event-title">
                        <h3 class="mb-3 text-warning event-title"><%= event.title %></h3>
                        <p class="text-white mb-0">
                          <% if event.start_date.present? && event.finish_date.present? %>
                            <span class="pr-3"><i class="fas fa-clock"></i> <%= event.start_date.strftime("%H:%M %p") %> - <%= event.finish_date.strftime("%H:%M %p") %></span>
                          <% end %>
                          <% if event.venue.present? %>
                            <i class="fas fa-location-arrow"></i> <%= event.venue.title %>
                          <% end %>
                        </p>
                      </td>
                      <td class="table-cell-item text-center">
                        <% if event.currency.present? && event.price.present? %>
                          <p class="text-white mb-0">
                            <% if event.price <= 0 %>
                              <strong>FREE</strong>
                            <% else %>
                              <strong><%= event.currency.upcase %> <%= number_to_human(event.price) %></strong>
                            <% end %>
                          </p>
                        <% else %>
                          <p class="text-white mb-0">
                            <strong>FREE</strong>
                          </p>
                        <% end %>
                      </td>
                      <td class="table-cell-item text-center">
                        <a href="<%= event_path(event) %>" class="btn btn-warning">More Info</a>
                      </td>
                    </tr>
                  <% end%>
                </table>
              </div>
            </div>
          </div>
          <div class="row mb-4">
            <div class="col-md-12 text-center">
              <%= paginate @events %>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>
<%= show_popup(0) %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page"><a href="<%= events_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item active"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/events/index.html.erb
<%- model_class = Event -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title">
        <%= action_name.capitalize unless action_name == 'index' %> <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
      </h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
            <li class="breadcrumb-item active">
              <%= if action_name == 'index'
                'All'
              else
                action_name.capitalize
              end %>
              <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <%= link_to "<i class='fas fa-plus-circle'></i> Add New".html_safe, new_event_path, :class => 'btn waves-effect waves-light btn-rounded btn-success mb-2' %>
      <%= render :partial => 'nav_buttons' %>
      <%= render :partial => 'search' %>
      <div class="card">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th class="text-center text-uppercase"><%= model_class.human_attribute_name(:id) %></th>
                  <th class="text-center text-capitalize"><%= model_class.human_attribute_name(:title) %></th>
                  <th class="text-center text-capitalize"><%= model_class.human_attribute_name(:status) %></th>
                  <th class="text-center text-capitalize">Event Date</th>
                  <th class="text-center text-capitalize">
                    Categories
                  </th>
                  <th class="text-center text-capitalize">Date</th>
                  <th class="text-center text-capitalize"><%=t '.actions', :default => t("helpers.actions") %></th>
                </tr>
              </thead>
              <tbody>
                <%= render :partial => 'table_event' %>
              </tbody>
            </table>
            <%= paginate @events %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<%- model_class = Event -%>
<div class="background-parallax" style="background-image:url('<%= asset_path('djvideo2.jpg') %>'); ">
  <div class="background-layer-opacity-black">
  </div>
  <div class="container">
    <section class="mb-6 pt-5">
      <div class="row">
        <div class="col-md-9">
          <div class="col-md-12 section-title-block mb-4">
            <h1 class="text-uppercase text-white page-title"><%= @event.title %></h1>
          </div>
          <div class="row">
            <div class="col-md-4 text-white mb-4">
              <% if @event.feature_image.present? %>
                <img src="<%= @event.feature_image.url %>" alt="" class="w-100 mb-3">
              <% end %>
              <% if @event.start_date.present? %>
                <p>
                  <strong class="text-warning">Date:</strong><br>
                  <%= @event.start_date.strftime("%B %d, %Y at %H:%M %p") %>
                </p>
              <% end %>
              <% if @event.venue.present? %>
                <p>
                  <strong class="text-warning">Address:</strong><br>
                  <%= @event.venue.title %><br>
                  <%= @event.venue.address if @event.venue.address.present? %>
                </p>
              <% end %>
              <% if @event.start_date.present? && @event.finish_date.present? %>
              <p>
                <strong class="text-warning">Time:</strong><br>
                <%= @event.start_date.strftime("%H:%M %p")  %> - <%= @event.finish_date.strftime("%H:%M %p") %>
              </p>
              <% end %>
              <% if @event.currency.present? && @event.price.present? %>
                <p class="text-white mb-0">
                  <% if @event.price <= 0 %>
                    <a href="#" class="btn btn-warning">Free</a>
                  <% else %>
                    <a href="#" class="btn btn-warning">Buy Ticket <%= @event.currency.upcase %> <%= number_to_human(@event.price) %></a>
                  <% end %>
                </p>
              <% else %>
                <p class="text-white mb-0">
                  <a href="#" class="btn btn-warning">Free</a>
                </p>
              <% end %>
            </div>
            <div class="col-md-8 text-white text-content">
              <%= @event.content.html_safe %>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="col-md-12 section-title-block mb-4">
            <h2 class="text-uppercase text-white section-title">upcoming events</h2>
          </div>
          <% @events.limit(3).each do |event| %>
            <div class="row mb-5">
              <div class="col-md-12">
                <h3 class="mb-3 text-warning event-title"><%= event.title %></h3>
              </div>
              <div class="col-md-3 col-3">
                <% if event.start_date.present? %>
                <p class="text-white text-center">
                  <span class="event-day-number"><%= event.start_date.strftime("%d") %></span><br>
                  <span><%= event.start_date.strftime("%b") %></span>
                </p>
                <% end %>
              </div>
              <div class="col-md-9 col-9">
                <% if event.start_date.present? && event.finish_date.present? %>
                  <p class="text-white"><i class="fas fa-clock"></i> <%= event.start_date.strftime("%H:%M %p") %> - <%= event.finish_date.strftime("%H:%M %p") %></p>
                <% end %>
                <% if event.venue.present? %>
                  <p class="text-white"><i class="fas fa-location-arrow"></i> <%= event.venue.title %></p>
                <% end %>
              </div>
              <div class="col-md-12 text-right">
                <a href="<%= event_path(event) %>" class="btn btn-warning">More Details</a>
              </div>
            </div>
          <% end %>
          <div class="row">
            <div class="col-md-12 text-center">
              <a href="<%= events_all_path %>" class="btn btn-lg btn-outline-warning">View More</a>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>
<%= show_popup(0) %>