config/routes.rb
Rails.application.routes.draw do
  resources :popups
  mount Ckeditor::Engine => '/ckeditor'
  root 'pages#home'
  get 'pages/galleries' => 'pages#galleries'
  get 'setting/general' => 'setups#general'
  resources :setups
  get 'genres/search' => 'genres#search'
  resources :genres
  get 'artists/search' => 'artists#search'
  get 'artists/all' => 'artists#all'
  resources :contacts
  resources :artists
  resources :images
  resources :venues
  get 'events/all' => 'events#all'
  get 'events/preview/:id' => 'events#preview', as: :events_preview
  get 'events/search' => 'events#search'
  get 'events/to_trash/:id' => 'events#to_trash', as: :events_to_trash
  resources :events
  get 'posts/all' => 'posts#all'
  get 'posts/preview/:id' => 'posts#preview', as: :posts_preview
  get 'posts/search' => 'posts#search'
  get 'posts/to_trash/:id' => 'posts#to_trash', as: :posts_to_trash
  resources :posts do
    resources :videos
    resources :audios
  end
  get 'pages/preview/:id' => 'pages#preview', as: :pages_preview
  get 'pages/search' => 'pages#search'
  get 'pages/to_trash/:id' => 'pages#to_trash', as: :pages_to_trash
  resources :pages
  get 'categories/search' => 'categories#search'
  resources :categories
  get 'cms-admin' => 'cms_admin#index'
  devise_for :users
  resources :users
  resources :tags
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :posts
  has_and_belongs_to_many :events
  has_many :subcategories, :class_name => "Category", :foreign_key => :parent_id, :dependent => :destroy
  belongs_to :parent, :class_name => "Category", :foreign_key => :parent_id, optional: true

  extend FriendlyId
  friendly_id :name, use: :slugged
  scope :noparent, -> {where(parent_id: [nil,""])}
  validates :name, presence: true

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  layout 'admin'
  # GET /categories
  # GET /categories.json
  def index
    @category = nil
    @categories = Category.all.order(:name)
    @categories = Kaminari.paginate_array(@categories).page(params[:page]).per(20)
  end

  def search
    if params[:keyword].present?
      @categories = Category
      if params[:keyword].present?
        if Rails.env.production?
          @categories = @categories.where(["categories.name ILIKE ?", "%#{params[:keyword]}%"])
        else
          @categories = @categories.where(["categories.name LIKE ?", "%#{params[:keyword]}%"])
        end
      end
      @categories = Kaminari.paginate_array(@categories).page(params[:page]).per(20)
    else
      @categories = Category.order(created_at: :desc)
      @categories = Kaminari.paginate_array(@categories).page(params[:page]).per(20)
    end
    render 'index'
  end
  

  # GET /categories/1
  # GET /categories/1.json
  def show
    @categories = @category.subcategories
  end

  # GET /categories/new
  def new
    @category = Category.new
    @category.parent = Category.find(params[:id]) unless params[:id].nil?
    @category_parent = Category.noparent
  end

  # GET /categories/1/edit
  def edit
    @category_parent = Category.noparent
  end

  # POST /categories
  # POST /categories.json
  def create
    @category_parent = Category.noparent
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    @category_parent = Category.noparent
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :slug, :description, :parent_id, :seo_title, :focus_keyphrase, :meta_description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def order_by_subcategories
    categories = Array.new
    query = Category.where(parent_id: nil).order(:name)
    query.each do |item|
      categories.push(item)
      if item.subcategories.present?
        item.subcategories.each do |sub|
          categories.push(sub)
        end
      end
    end
    return categories
  end
end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-danger" role="alert">
        <h3 class="alert-heading"><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h3>
        <ul>
          <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <%= form_for @category, :html => { :class => "form-horizontal category" } do |f| %>
          <div class="row form-group">
            <%= f.label :name, :class => 'col-form-label col-lg-2' %>
            <div class="col-lg-4">
              <%= f.text_field :name, :class => 'form-control' %>
              <%=f.error_span(:name) %>
            </div>
            <div class="col-md-6">
              <small><em>*required</em></small>
            </div>
          </div>
          <% unless @category.new_record? %>
            <div class="row form-group">
              <%= f.label :slug, :class => 'col-form-label col-lg-2' %>
              <div class="col-lg-4">
                <%= f.text_field :slug, :class => 'form-control', :required => true %>
                <%=f.error_span(:slug) %>
              </div>
            </div>
          <% end %>
          <div class="row form-group">
            <%= f.label :description, :class => 'col-form-label col-lg-2' %>
            <div class="col-lg-4">
              <%= f.text_area :description, :class => 'form-control' %>
            </div>
            <%=f.error_span(:description) %>
          </div>
          <div class="row form-group">
            <%= f.label :parent_id, :class => 'col-form-label col-lg-2' %>
            <div class="col-lg-4">
              <%= f.select :parent_id, @category_parent.map {|s| [s.name, s.id ]},{:include_blank => '-Choose Parent Category-'}, :class=>"form-control w-100 select2"%>
              <%=f.error_span(:parent_id) %>
            </div>
          </div>
          <div class="row form-group">
            <%= f.label :seo_title, :class => 'col-form-label col-lg-2 text-capitalize' %>
            <div class="col-lg-4">
              <%= f.text_field :seo_title, :class => 'form-control' %>
              <%=f.error_span(:seo_title) %>
            </div>
          </div>
          <div class="row form-group">
            <%= f.label :focus_keyphrase, :class => 'col-form-label col-lg-2 text-capitalize' %>
            <div class="col-lg-4">
              <%= f.text_field :focus_keyphrase, :class => 'form-control' %>
              <%=f.error_span(:focus_keyphrase) %>
            </div>
          </div>
          <div class="row form-group">
            <%= f.label :meta_description, :class => 'col-form-label col-lg-2 text-capitalize' %>
            <div class="col-lg-4">
              <%= f.text_area :meta_description, :class => 'form-control' %>
              <%=f.error_span(:meta_description) %>
            </div>
          </div>
          <div class="row form-group">
            <div class="col-md-10 offset-md-2">
              <%= f.submit nil, :class => 'btn btn-success' %>
              <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              categories_path, :class => 'btn btn-secondary' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/_search.html.erb
<div class="mb-1">
    <%= form_tag({action: :search}, method: 'get') do %>
        <div class="form-row">
            <div class="input-group mb-2 col">
                <%= text_field_tag :keyword, (params[:keyword] or '') , options={class: "form-control", placeholder: "Insert Keyword Here"} %>
            </div>
            <button type="submit" class="btn btn-primary mb-2">Search</button>
        </div>
    <% end %>
</div>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page"><a href="<%= categories_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item active"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page">
              <a href="<%= categories_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a>
            </li>
            <li class="breadcrumb-item active">All <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <%= link_to "<i class='fas fa-plus-circle'></i> Add New".html_safe, new_category_path, :class => 'btn waves-effect waves-light btn-rounded btn-success mb-2' %>
      <%= render :partial => 'search' %>
      <div class="card">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th class="text-center text-uppercase"><%= model_class.human_attribute_name(:id) %></th>
                  <th class="text-center"><%= model_class.human_attribute_name(:name) %></th>
                  <th class="text-center"><%= model_class.human_attribute_name(:slug) %></th>
                  <th class="text-center"><%= model_class.human_attribute_name(:parent_id) %></th>
                  <th class="text-center"><%= model_class.human_attribute_name(:created_at) %></th>
                  <th class="text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
                </tr>
              </thead>
              <tbody>
                <% @categories.each do |category| %>
                  <tr>
                    <td class="text-center"><%= link_to category.id, category_path(category) %></td>
                    <td class="text-center"><%= category.name %></td>
                    <td class="text-center"><%= category.slug %></td>
                    <td class="text-center"><%= category.parent.name rescue '-' %></td>
                    <td class="text-center"><%= category.created_at.strftime("%Y/%m/%d@%H:%M:%S") %></td>
                    <td class="text-center">
                      <%= link_to "<i class='fas fa-eye'></i> Show".html_safe, category_path(category), :class => 'btn-sm waves-effect waves-light btn-info mb-1' %>
                      <%= link_to "<i class='fas fa-edit'></i> Edit".html_safe, edit_category_path(category), :class => 'btn-sm waves-effect waves-light btn-warning mb-1' %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <%= paginate @categories %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page"><a href="<%= categories_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item active"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
            <li class="breadcrumb-item active"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-12 b-r">
              <strong>Name</strong><br>
              <p class="text-muted"><%= @category.name %></p>
            </div>
            <div class="col-md-12 b-r">
              <strong>Slug</strong><br>
              <p class="text-muted"><%= @category.slug %></p>
            </div>
            <div class="col-md-12 b-r">
              <strong>Parent Category</strong><br>
              <p class="text-muted"><%= @category.parent.name if @category.parent.present? %></p>
            </div>
            <div class="col-md-12 b-r">
              <strong>Description</strong><br>
              <p class="text-muted"><%= @category.description %></p>
            </div>
            <div class="col-md-12 text-center">
              <hr>
              <%= link_to t('.back', :default => t("helpers.links.back")), categories_path, :class => 'btn waves-effect waves-light btn-secondary mb-1' %>
              <%= link_to "<i class='fas fa-edit'></i> Edit".html_safe, edit_category_path(@category), :class => 'btn waves-effect waves-light btn-warning mb-1' %>
              <%= link_to "<i class='fas fa-times-circle'></i> Destroy".html_safe, category_path(@category), :class => 'btn waves-effect waves-light btn-danger mb-1', :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>