config/routes.rb
Rails.application.routes.draw do
  resources :popups
  mount Ckeditor::Engine => '/ckeditor'
  root 'pages#home'
  get 'pages/galleries' => 'pages#galleries'
  get 'setting/general' => 'setups#general'
  resources :setups
  get 'genres/search' => 'genres#search'
  resources :genres
  get 'artists/search' => 'artists#search'
  get 'artists/all' => 'artists#all'
  resources :contacts
  resources :artists
  resources :images
  resources :venues
  get 'events/all' => 'events#all'
  get 'events/preview/:id' => 'events#preview', as: :events_preview
  get 'events/search' => 'events#search'
  get 'events/to_trash/:id' => 'events#to_trash', as: :events_to_trash
  resources :events
  get 'posts/all' => 'posts#all'
  get 'posts/preview/:id' => 'posts#preview', as: :posts_preview
  get 'posts/search' => 'posts#search'
  get 'posts/to_trash/:id' => 'posts#to_trash', as: :posts_to_trash
  resources :posts do
    resources :videos
    resources :audios
  end
  get 'pages/preview/:id' => 'pages#preview', as: :pages_preview
  get 'pages/search' => 'pages#search'
  get 'pages/to_trash/:id' => 'pages#to_trash', as: :pages_to_trash
  resources :pages
  get 'categories/search' => 'categories#search'
  resources :categories
  get 'cms-admin' => 'cms_admin#index'
  devise_for :users
  resources :users
  resources :tags
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/popup.rb
class Popup < ApplicationRecord
  mount_uploader :image, FeatureUploader
  POSITION = ["All Page", "Homepage"]
  SIZE = {small: "modal-sm", default: "modal-default", large: "modal-lg", xlarge: "modal-xl"}
  validates :name, presence: true
  validates :size, presence: true
  validates :position, presence: true
end

app/controllers/popups_controller.rb
class PopupsController < ApplicationController
  before_action :set_popup, only: [:show, :edit, :update, :destroy]
  layout 'admin'
  # GET /popups
  # GET /popups.json
  def index
    @popups = Popup.all
    @popup_position = Popup::POSITION
  end

  # GET /popups/new
  def new
    @popup = Popup.new
  end

  # GET /popups/1/edit
  def edit
  end

  # POST /popups
  # POST /popups.json
  def create
    @popup = Popup.new(popup_params)

    respond_to do |format|
      if @popup.save
        format.html { redirect_to popups_path, notice: 'Popup was successfully created.' }
        format.json { render :index, status: :created, location: @popup }
      else
        format.html { render :new }
        format.json { render json: @popup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /popups/1
  # PATCH/PUT /popups/1.json
  def update
    respond_to do |format|
      if @popup.update(popup_params)
        format.html { redirect_to popups_path, notice: 'Popup was successfully updated.' }
        format.json { render :show, status: :ok, location: @popup }
      else
        format.html { render :edit }
        format.json { render json: @popup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /popups/1
  # DELETE /popups/1.json
  def destroy
    @popup.destroy
    respond_to do |format|
      format.html { redirect_to popups_url, notice: 'Popup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_popup
      @popup = Popup.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def popup_params
      params.require(:popup).permit(:caption, :position, :image, :link, :size, :name)
    end
end

app/helpers/popups_helper.rb
module PopupsHelper

  def show_popup(page_position)

    if page_position == 1
      q = Popup.where(position: page_position)
    else
      q = Popup.where(position: 0)
    end
    render partial: "popups/pop", locals: { data: q }
  end
end

app/views/popups/_form.html.erb
<% if @popup.errors.any? %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-danger" role="alert">
        <h3 class="alert-heading"><%= pluralize(@popup.errors.count, "error") %> prohibited this pop up from being saved:</h3>
        <ul>
          <% @popup.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>
<%= form_for @popup, :html => { :class => "form-horizontal popup" } do |f| %>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <div class="form-group">
            <%= f.label :name %> <small><em>*required</em></small>
            <%= f.text_field :name, :class => 'form-control', required: true %>
            <%=f.error_span(:name) %>
          </div>
          <div class="form-group">
            <%= f.label :image %>
            <% if @popup.image.nil? || @popup.image.blank? %>
            <%= f.file_field :image, :class => 'dropify','data-max-file-size'=>'1M' %>
            <% else %>
            <%= f.file_field :image, :class => 'dropify','data-max-file-size'=>'1M', 'data-default-file' => @popup.image.url %>
            <% end %>
            <%=f.error_span(:image) %>
          </div>
          <div class="form-group">
            <%= f.label :link %>
            <%= f.text_field :link, :class => 'form-control' %>
            <%=f.error_span(:link) %>
          </div>
          <div class="form-group">
            <%= f.label :position %> <small><em>*required</em></small>
            <%= f.select :position, Popup::POSITION.each_with_index.map {|r, i| [r, i]}, {:include_blank => '- Choose Position -'}, :class => 'form-control', required: true %>
            <%=f.error_span(:position) %>
          </div>
          <div class="form-group">
            <%= f.label :size %> <small><em>*required</em></small>
            <%= f.select :size, Popup::SIZE.map {|x, y| [x.upcase, y]}, {:include_blank => '- Choose Size -'}, :class => 'form-control', required: true %>
            <%=f.error_span(:size) %>
          </div>
          <div class="form-group">
            <%= f.label :caption %>
            <%= f.cktext_area :caption, :class => 'form-control', :ckeditor => {:customConfig => '/assets/ckeditor/config_popup.js'} %>
            <%=f.error_span(:caption) %>
          </div>
          <div class="form-group text-center">
            <hr>
            <%= f.submit 'Save', :class => 'btn btn-success' %>
            <%= link_to t('.cancel', :default => t("helpers.links.cancel")), popups_path, :class => 'btn btn-secondary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/popups/_pop.html.erb
<% data.each do |popup| %>
  <div class="modal fade modal-popup" id="modal-<%= popup.id %>">
    <div class="modal-dialog modal-dialog-centered <%= popup.size %>">
      <div class="modal-content">
        <div class="">
          <% if popup.image.present? %>
            <a href="<%= popup.link if popup.link.present? %>" target="_blank">
              <img src="<%= popup.image.url %>" class="w-100" alt="<%= popup.name %>">
            </a>
          <% end %>
        </div>
        <% if popup.caption.present? %>
          <div class="p-2">
            <%= popup.caption.html_safe %>
          </div>
        <% end %>
        <button type="button" class="btn btn-outline-warning" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
<% end %>
<script type="text/javascript">
  $(document).ready(function() {
    $('.modal-popup').modal('show');
  })
</script>

app/views/popups/edit.html.erb
<%- model_class = Popup -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page"><a href="<%= popups_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item active"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/popups/index.html.erb
<%- model_class = Popup -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title">
        <%= action_name.capitalize unless action_name == 'index' %> <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
      </h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
            <li class="breadcrumb-item active">
              <%= if action_name == 'index'
                'All'
              else
                action_name.capitalize
              end %>
              <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <a href="<%= new_popup_path %>" class="btn btn-success mb-2 btn-rounded"><i class="fas fa-plus-circle"></i> Add New</a>
      <div class="card">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th class="text-center"><%= model_class.human_attribute_name(:id) %></th>
                  <th class="text-center"><%= model_class.human_attribute_name(:name) %></th>
                  <th class="text-center"><%= model_class.human_attribute_name(:position) %></th>
                  <th class="text-center"><%= model_class.human_attribute_name(:created_at) %></th>
                  <th class="text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
                </tr>
              </thead>
              <tbody>
                <% @popups.each do |popup| %>
                  <tr>
                    <td class="text-center"><%= link_to popup.id, popup_path(popup) %></td>
                    <td class="text-center"><%= popup.name %></td>
                    <td class="text-center"><%= @popup_position[popup.position.to_i] %></td>
                    <td class="text-center"><%= popup.created_at.strftime("%Y/%m/%d@%H:%M:%S") rescue '-' %></td>
                    <td class="text-center">
                      <button type="button" name="button" class="btn btn-default btn-xs" data-toggle="modal" data-target="#modal-<%= popup.id %>">
                        <i class='fas fa-eye'></i> Show
                      </button>
                      <%= link_to "<i class='fas fa-edit'></i> Edit".html_safe, edit_popup_path(popup), :class => 'btn btn-warning btn-xs' %>
                      <%= link_to "<i class='fas fa-times-circle'></i> Destroy".html_safe, popup_path(popup), :class => 'btn btn-xs btn-danger', :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
                    </td>
                  </tr>
                  <div class="modal fade" id="modal-<%= popup.id %>">
                    <div class="modal-dialog modal-dialog-centered <%= popup.size %>">
                      <div class="modal-content">
                        <div class="">
                          <% if popup.image.present? %>
                            <a href="<%= popup.link if popup.link.present? %>" target="_blank">
                              <img src="<%= popup.image.url %>" class="w-100" alt="<%= popup.name %>">
                            </a>
                          <% end %>
                        </div>
                        <% if popup.caption.present? %>
                          <div class="p-2">
                            <%= popup.caption.html_safe %>
                          </div>
                        <% end %>
                        <hr>
                        <button type="button" class="btn btn-outline-warning" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/popups/new.html.erb
<%- model_class = Popup -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item" aria-current="page"><a href="<%= popups_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item active"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/popups/show.html.erb
<%- model_class = Popup -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:caption) %>:</strong></dt>
  <dd><%= @popup.caption %></dd>
  <dt><strong><%= model_class.human_attribute_name(:position) %>:</strong></dt>
  <dd><%= @popup.position %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @popup.image %></dd>
  <dt><strong><%= model_class.human_attribute_name(:link) %>:</strong></dt>
  <dd><%= @popup.link %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              popups_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_popup_path(@popup), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              popup_path(@popup),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>